name: Lint and build on Commit
on:
  push:
    branches:
      - '**'

jobs:
  lint-client:
    runs-on: ubuntu-latest
    container:
      image: node:24
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run build
